---

# Create rpmfbender user
- name: Add rpmfbender user in local backend (service user) 
  shell: "sfmanager --url http://{{ fqdn }} --auth admin:{{ admin_password }} user create --username rpmfbender --password {{ rpmfbender_password  }} --email 'dev-robot@{{ fqdn }}' --fullname 'Bender RPM Factory' --ssh-key /root/sf-bootstrap-data/ssh_keys/jenkins_rsa"
- name: Activate rpmfbender user (force cauth to register the user)
  shell: "sfmanager --url http://{{ fqdn }} --auth rpmfbender:{{ rpmfbender_password }} user update --username rpmfbender --password {{ rpmfbender_password  }}"

# Create and maintain updated gating_scripts repo
- include: project_create.yaml project=gating_scripts
- copy: src=../files/gating/ dest=build-gating_scripts/
- name: Add rpmfactory gating scripts
  shell: chdir=build-gating_scripts {{ item }}
  with_items:
    - "git review -s"
    - "test -n \"$(git ls-files -o -m --exclude-standard)\" && git add -A . && git commit -m 'Update gating scripts' || true"
    - "git push -f gerrit"

# Push rpmfactory jjb in the config repo
- name: Reset local config repo
  shell: chdir=config {{ item }}
  with_items:
    - "git fetch --all"
    - "git reset --hard origin/master --"
    - "git clean -f -d"
- copy: src=../files/jobs/rpmfactory.yaml dest=config/jobs/rpmfactory.yaml
- copy: src=../files/nodepool/rpmfactory-base.sh dest=config/nodepool/rpmfactory-base.sh
- name: Add jobs to local config repo
  shell: chdir=config {{ item }}
  with_items:
    - "test -n \"$(git ls-files -o -m --exclude-standard)\" && git add -A . && git commit -m 'Add rpmfactory jobs' || true"
- name: Check for a gating script update
  command: chdir=config git diff HEAD origin/master
  register: diff
- name: Submit jobs to config repo and wait for validation before submition
  when: diff.stdout != ''
  shell: chdir=config submit_and_wait.py --approve
