---

# Create and maintain updated gating_scripts repo
- include: project_create.yaml project=gating_scripts
- copy: src=../../../../gating/ dest=build-gating_scripts/
- name: Add rpmfactory gating scripts
  shell: chdir=build-gating_scripts {{ item }}
  with_items:
    - "git review -s"
    - "test -n \"$(git ls-files -o -m --exclude-standard)\" && git commit -a -m 'Update gating scripts' || true"
    - "git push -f gerrit"

# Push rpmfactory jjb in the config repo
- name: Reset local config repo
  shell: chdir=config {{ item }}
  with_items:
    - "git fetch --all"
    - "git reset --hard origin/master --"
    - "git clean -f -d"
- copy: src=../../../../config/jobs/projects.yaml dest=config/jobs/rpmfactory.yaml
- name: Add jobs to local config repo
  shell: chdir=config {{ item }}
  with_items:
    - "git add jobs/rpmfactory.yaml"
    - "test -n \"$(git ls-files -o -m --exclude-standard)\" && git commit -m 'Add rpmfactory jobs' || true"
- name: Check for a gating script update
  command: chdir=config git diff HEAD origin/master
  register: diff
- name: Submit jobs to config repo and wait for validation before submition
  when: diff.stdout != ''
  shell: chdir=config {{ item }}
    - "submit_and_wait.py --approve"
