---

- name: Fix rights on builder topdir
  shell: "/bin/chcon -R -t public_content_rw_t {{ koji_builder_topdir }} && touch /home/kojiadmin/.koji/.rightbuilders.done"
  args:
    creates: /home/kojiadmin/.koji/.rightbuilders.done
  tags:
    - koji-rpmfactory

- name: Add and configure builders | Do add koji-builder01 to database
  become: yes
  become_user: kojiadmin
  shell: "/usr/local/bin/setup-koji.sh koji-builder01 && touch /home/kojiadmin/.koji/.addbuilders.done"
  args:
    creates: /home/kojiadmin/.koji/.addbuilders.done
  with_items: groups.koji_rpmfactory
  tags:
    - koji-rpmfactory
    - kojiadmin-add-hosts
