---
# SF Access
fqdn: "rpmfactory.sftests.com"
admin_password: "userpass"

# Defaut for bender service user
bender_name: "sfrdobender"
bender_email_name: "sfrdobender"
# Please set a strong one
bender_password: "pwdtochange"

# Koji server
koji_server: "koji.rpmfactory.sftests.com"
koji_client_cert_path: "/tmp/jenkins-koji.tgz"
