---

- name: Copy mirror script
  copy: src=mirror-cloud.sh dest=/usr/local/bin/ owner=root group=root mode=0755
  tags:
    - mirror-rpmfactory

- name: Install required Packages
  yum: name={{item}} state=installed
  when: ansible_distribution_major_version == '7'
  with_items:
    - https://kojipkgs.fedoraproject.org/packages/createrepo/0.10.3/3.fc21/noarch/createrepo-0.10.3-3.fc21.noarch.rpm
    - wget
    - httpd
    - rsync
  tags:
    - mirror-rpmfactory

- name: Create directory for RDO mirror
  file: path=/srv/mirror/centos/7/cloud state=directory mode=0755

- name: Create the symlink for HTTP access
  file: src=/srv/mirror dest=/var/www/html/mirror state=link

- name: Populate or update RDO mirror
  command: /usr/local/bin/mirror-cloud.sh
  args:
    chdir: /srv/mirror/centos/7/cloud
    creates: /srv/mirror/centos/7/cloud/x86_64/openstack-liberty
