labels:
  - name: bare-centos-7
    image: bare-centos-7
    min-ready: 0
    providers:
      - name: default
  - name: koji-centos-7
    image: koji-centos-7
    min-ready: 5
    providers:
      - name: default
