- job:
    name: 'package-validate'
    defaults: global
    builders:
      - base-pkg-validation:
          buildtarget: "centos7"
      - shell: |
          echo "Passed !"
    triggers:
      - zuul
    node: rpmfactory-base-worker

- job:
    name: 'package-export'
    defaults: global
    builders:
      - base-pkg-exportation:
          buildtarget: "centos7"
      - shell: |
          echo "Simulate export ..."
          echo "Exported !"
    triggers:
      - zuul
    node: rpmfactory-base-worker
