---
galaxy_info:
  author: Sebastien Badia
  description: Installs Koji's RPM Factory for RedHat
  license: license (GPLv3)
  min_ansible_version: 1.9.1
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - development
  - packaging
  - system
dependencies: []
