---

#- include: project_create.yaml project=testpkg
#- name: Reset config
#  command: chdir=config {{ item }}
#  with_items:
#    - git fetch --all
#    - git reset --hard origin/master --
#
#- name: Add jjb testpkg
#  command: >
#    hieraedit.py --yaml config/jobs/projects.yaml --eval --append 0 \
#        "{'project': {'name': 'testpkg',
#          'jobs': ['{name}-unit-tests', '{name}-functional-tests']
#        }}"
#
#- name: Add zuul testpkg
#  command: >
#    hieraedit.py --yaml config/zuul/projects.yaml --eval --append projects \
#        "{'name': 'testpkg',
#           'check': ['testpkg-unit-tests',],
#           'gate': ['testpkg-unit-test', 'testpkg-functional-tests'],
#        }"
#
#- name: Commit config-repo change
#  command: chdir=config  {{ item }}
#  with_items:
#      - 'git commit -a -m "Adds testpkg project"'
#      - 'submit_and_wait.py --approve'
#
#- include: gate_check.yml project=testpkg
#
##- include: "project_create.yaml"
#
##- stat: path=/var/lib/jenkins/jobs/{{ project }}-unit_tests
##  register: job_created
#
##- include: "configrepo.yml"
##  when: job_created.stat.isdir is not defined
#
#
