---
- name: Wait for cloud-init success
  wait_for: path=/var/log/cloud-init-output.log search_regex="^SUCCESS 1node-allinone$"

- include: "project_create.yaml"

- stat: path=/var/lib/jenkins/jobs/{{ project }}-unit_tests
  register: job_created

- include: "configrepo.yml"
  when: job_created.stat.isdir is not defined

#- include: "gate_conflict_check.yml"

