---
- hosts: managesf
  user: root
  gather_facts: no
  roles:
    - sf-nodepool
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.local/bin:/root/bin"

- hosts: koji_db
  roles:
    - epel

- hosts: koji_db
  roles:
    - patrik.uytterhoeven.PostgreSQL-For-RHEL6x
    - koji-db

- hosts: koji_ca
  roles:
    - koji-ca

- hosts: koji_hub
  roles:
    - koji-hub
    - koji-kojira

- hosts: koji_web
  roles:
    - koji-web

- hosts: mirror_rpmfactory
  roles:
    - mirror-rpmfactory

- hosts: koji_builder
  roles:
    - koji-rpmfactory
    - koji-builder
