---
- name: Wait for cloud-init success
  wait_for: path=/var/log/cloud-init-output.log search_regex="^SUCCESS 1node-allinone$"

- include: "sfconfig.yml"
- include: "configrepo.yml"
- include: "wait.yml"
